"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";
import { saveLessonAction } from "@/app/admin/courses/actions";

type Question = { question: string; question_type: "single" | "multiple" | "boolean"; options: { text: string; is_correct: boolean }[] };
type Initial = { id?: string; moduleId: string; title?: string; description?: string | null; lessonType: "theory" | "video" | "quiz" | "assignment"; isRequired?: boolean; isPreview?: boolean; content?: string; videoId?: string; durationSeconds?: number | null; instructions?: string; allowText?: boolean; allowLink?: boolean; allowFile?: boolean; allowResubmission?: boolean; maxAttempts?: number | null; questions?: Question[] };

export function LessonEditor({ courseId, modules, initial }: { courseId: string; modules: { id: string; title: string }[]; initial: Initial }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  const [kind, setKind] = useState(initial.lessonType); const [questions, setQuestions] = useState<Question[]>(initial.questions ?? []);
  const quizJson = useMemo(() => JSON.stringify(questions), [questions]);
  function updateQuestion(index: number, patch: Partial<Question>) { setQuestions((all) => all.map((q, i) => i === index ? { ...q, ...patch } : q)); }
  return <form className="card stack" action={(data) => startTransition(async () => { const result = await saveLessonAction(courseId, initial.id ?? null, data); setMessage(result.message); if (result.ok) { router.push(`/admin/courses/${courseId}/edit`); router.refresh(); } })}>
    {message && <p className={message.includes("сохран") ? "notice success" : "notice"}>{message}</p>}
    <div className="form-grid"><label className="field"><span>Модуль</span><select name="moduleId" defaultValue={initial.moduleId}>{modules.map((m) => <option value={m.id} key={m.id}>{m.title}</option>)}</select></label><label className="field"><span>Тип урока</span><select name="lessonType" value={kind} onChange={(e) => setKind(e.target.value as Initial["lessonType"])} disabled={Boolean(initial.id)}><option value="theory">Теория</option><option value="video">Видео</option><option value="quiz">Тест</option><option value="assignment">Задание</option></select>{initial.id && <input type="hidden" name="lessonType" value={kind} />}</label></div>
    <label className="field"><span>Название *</span><input name="title" required minLength={2} defaultValue={initial.title ?? ""} /></label>
    <label className="field"><span>Описание</span><textarea name="description" rows={3} defaultValue={initial.description ?? ""} /></label>
    <div className="actions"><label className="topic-option"><input type="checkbox" name="isRequired" defaultChecked={initial.isRequired ?? true} />Обязательный</label><label className="topic-option"><input type="checkbox" name="isPreview" defaultChecked={initial.isPreview ?? false} />Открытый preview</label></div>
    {kind === "theory" && <label className="field"><span>Текст урока (Markdown)</span><textarea name="content" rows={16} defaultValue={initial.content ?? ""} /></label>}
    {kind === "video" && <><label className="field"><span>YouTube URL или ID</span><input name="videoUrl" required defaultValue={initial.videoId ?? ""} /></label><label className="field"><span>Длительность, секунд</span><input name="durationSeconds" type="number" min="0" defaultValue={initial.durationSeconds ?? ""} /></label></>}
    {kind === "assignment" && <><label className="field"><span>Инструкция</span><textarea name="instructions" required rows={10} defaultValue={initial.instructions ?? ""} /></label><div className="topic-grid">{[["allowText","Текст",initial.allowText ?? true],["allowLink","Ссылка",initial.allowLink],["allowFile","Файл",initial.allowFile],["allowResubmission","Повторная отправка",initial.allowResubmission]].map(([name,label,checked]) => <label className="topic-option" key={String(name)}><input type="checkbox" name={String(name)} defaultChecked={Boolean(checked)} />{label}</label>)}</div></>}
    {kind === "quiz" && <div className="stack"><label className="field"><span>Максимум попыток (пусто — без ограничения)</span><input name="maxAttempts" type="number" min="1" defaultValue={initial.maxAttempts ?? ""} /></label><input type="hidden" name="quizJson" value={quizJson} />{questions.map((q, qi) => <div className="quiz-question stack compact" key={qi}><div className="actions"><strong>Вопрос {qi + 1}</strong><button type="button" className="link-button danger" onClick={() => setQuestions((all) => all.filter((_, i) => i !== qi))}>Удалить</button></div><input value={q.question} placeholder="Текст вопроса" onChange={(e) => updateQuestion(qi, { question: e.target.value })} /><select value={q.question_type} onChange={(e) => updateQuestion(qi, { question_type: e.target.value as Question["question_type"] })}><option value="single">Один ответ</option><option value="multiple">Несколько ответов</option><option value="boolean">Да / нет</option></select>{q.options.map((o, oi) => <label className="quiz-option" key={oi}><input type={q.question_type === "multiple" ? "checkbox" : "radio"} name={`correct-${qi}`} checked={o.is_correct} onChange={(e) => updateQuestion(qi, { options: q.options.map((x, i) => ({ ...x, is_correct: q.question_type === "multiple" ? i === oi ? e.target.checked : x.is_correct : i === oi })) })} /><input value={o.text} placeholder={`Вариант ${oi + 1}`} onChange={(e) => updateQuestion(qi, { options: q.options.map((x, i) => i === oi ? { ...x, text: e.target.value } : x) })} /></label>)}<button type="button" className="button small secondary" onClick={() => updateQuestion(qi, { options: [...q.options, { text: "", is_correct: false }] })}>Добавить вариант</button></div>)}<button type="button" className="button secondary" onClick={() => setQuestions((all) => [...all, { question: "", question_type: "single", options: [{ text: "", is_correct: true }, { text: "", is_correct: false }] }])}>Добавить вопрос</button></div>}
    <button className="button" disabled={pending}>{pending ? "Сохраняем…" : "Сохранить урок"}</button>
  </form>;
}
