"use client";

import { useRouter } from "next/navigation";
import { useMemo, useState, useTransition } from "react";
import { ArrowLeft, BookOpen, Check, ClipboardList, FileQuestion, Plus, Save, Trash2, Video } from "lucide-react";
import { saveLessonAction } from "@/app/admin/courses/actions";
import { getYouTubeId } from "@/lib/course-utils";

type Question = { question: string; question_type: "single" | "multiple" | "boolean"; options: { text: string; is_correct: boolean }[] };
type Initial = { id?: string; moduleId: string; title?: string; description?: string | null; lessonType: "theory" | "video" | "quiz" | "assignment"; isRequired?: boolean; isPreview?: boolean; content?: string; videoId?: string; durationSeconds?: number | null; instructions?: string; allowText?: boolean; allowLink?: boolean; allowFile?: boolean; allowResubmission?: boolean; maxAttempts?: number | null; questions?: Question[] };

export function LessonEditor({ courseId, modules, initial }: { courseId: string; modules: { id: string; title: string }[]; initial: Initial }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null);
  const [kind, setKind] = useState(initial.lessonType); const [questions, setQuestions] = useState<Question[]>(initial.questions ?? []);
  const [videoUrl, setVideoUrl] = useState(initial.videoId ?? "");
  const quizJson = useMemo(() => JSON.stringify(questions), [questions]);
  const videoId = getYouTubeId(videoUrl);
  function updateQuestion(index: number, patch: Partial<Question>) { setQuestions((all) => all.map((q, i) => i === index ? { ...q, ...patch } : q)); }
  const typeMeta = { theory: { label: "Теория", icon: BookOpen }, video: { label: "Видео", icon: Video }, quiz: { label: "Тест", icon: FileQuestion }, assignment: { label: "Задание", icon: ClipboardList } } as const;
  const CurrentIcon = typeMeta[kind].icon;
  return <form className="lesson-editor" action={(data) => startTransition(async () => { const result = await saveLessonAction(courseId, initial.id ?? null, data); setMessage(result.message); if (result.ok) { router.push(`/admin/courses/${courseId}/edit`); router.refresh(); } })}>
    <aside className="lesson-editor-sidebar"><button type="button" onClick={() => router.push(`/admin/courses/${courseId}/edit`)}><ArrowLeft aria-hidden="true" size={17} />К программе</button><div className="lesson-type-summary"><CurrentIcon aria-hidden="true" size={22} /><span><small>Тип урока</small><strong>{typeMeta[kind].label}</strong></span></div><div className="lesson-editor-toggles"><label><input type="checkbox" name="isRequired" defaultChecked={initial.isRequired ?? true} /><span><Check aria-hidden="true" size={14} />Обязательный</span></label><label><input type="checkbox" name="isPreview" defaultChecked={initial.isPreview ?? false} /><span><Check aria-hidden="true" size={14} />Открытый preview</span></label></div></aside>
    <div className="lesson-editor-main">
      {message && <p className={message.includes("сохран") ? "notice success" : "notice"} aria-live="polite">{message}</p>}
      <section className="lesson-editor-section"><header><p className="eyebrow">Настройки</p><h2>Основные сведения</h2></header><div className="form-grid"><label className="field"><span>Модуль</span><select name="moduleId" defaultValue={initial.moduleId}>{modules.map((m) => <option value={m.id} key={m.id}>{m.title}</option>)}</select></label><label className="field"><span>Тип урока</span><select name="lessonType" value={kind} onChange={(e) => setKind(e.target.value as Initial["lessonType"])} disabled={Boolean(initial.id)}><option value="theory">Теория</option><option value="video">Видео</option><option value="quiz">Тест</option><option value="assignment">Задание</option></select>{initial.id && <input type="hidden" name="lessonType" value={kind} />}</label></div><label className="field"><span>Название *</span><input name="title" required minLength={2} defaultValue={initial.title ?? ""} placeholder="Название урока" /></label><label className="field"><span>Описание</span><textarea name="description" rows={3} defaultValue={initial.description ?? ""} placeholder="Кратко опишите результат урока" /></label></section>
      <section className="lesson-editor-section lesson-content-editor"><header><p className="eyebrow">Содержание</p><h2>{typeMeta[kind].label}</h2></header>
        {kind === "theory" && <label className="field"><span>Текст урока (Markdown)</span><textarea className="theory-editor" name="content" rows={20} defaultValue={initial.content ?? ""} placeholder="# Заголовок урока" /></label>}
        {kind === "video" && <div className="video-editor-grid"><div className="stack"><label className="field"><span>YouTube URL или ID</span><input name="videoUrl" required value={videoUrl} onChange={(event) => setVideoUrl(event.target.value)} placeholder="https://youtube.com/watch?v=…" /></label><label className="field"><span>Длительность, секунд</span><input name="durationSeconds" type="number" min="0" defaultValue={initial.durationSeconds ?? ""} /></label></div><div className="studio-video-preview">{videoId ? <iframe src={`https://www.youtube-nocookie.com/embed/${videoId}`} title="Предпросмотр видео" allowFullScreen /> : <div><Video aria-hidden="true" size={30} /><span>Предпросмотр появится после корректной ссылки</span></div>}</div></div>}
        {kind === "assignment" && <><label className="field"><span>Инструкция</span><textarea name="instructions" required rows={12} defaultValue={initial.instructions ?? ""} placeholder="Опишите задачу, критерии и ожидаемый результат" /></label><fieldset className="assignment-methods"><legend>Разрешённые способы отправки</legend>{[["allowText","Текст",initial.allowText ?? true],["allowLink","Ссылка",initial.allowLink],["allowFile","Файл",initial.allowFile],["allowResubmission","Повторная отправка",initial.allowResubmission]].map(([name,label,checked]) => <label className="editor-check-option" key={String(name)}><input type="checkbox" name={String(name)} defaultChecked={Boolean(checked)} /><span><Check aria-hidden="true" size={15} />{label}</span></label>)}</fieldset></>}
        {kind === "quiz" && <div className="quiz-builder"><label className="field quiz-attempts"><span>Максимум попыток</span><input name="maxAttempts" type="number" min="1" defaultValue={initial.maxAttempts ?? ""} placeholder="Без ограничения" /></label><input type="hidden" name="quizJson" value={quizJson} />{questions.map((q, qi) => <article className="quiz-editor-question" key={qi}><header><span>{String(qi + 1).padStart(2, "0")}</span><strong>Вопрос {qi + 1}</strong><button type="button" className="link-button danger" onClick={() => setQuestions((all) => all.filter((_, i) => i !== qi))}><Trash2 aria-hidden="true" size={15} />Удалить</button></header><div className="quiz-question-fields"><label className="field"><span>Формулировка</span><input value={q.question} placeholder="Текст вопроса" onChange={(e) => updateQuestion(qi, { question: e.target.value })} /></label><label className="field"><span>Тип ответа</span><select value={q.question_type} onChange={(e) => updateQuestion(qi, { question_type: e.target.value as Question["question_type"] })}><option value="single">Один ответ</option><option value="multiple">Несколько ответов</option><option value="boolean">Да / нет</option></select></label></div><div className="quiz-editor-options"><span>Варианты · отметьте правильные</span>{q.options.map((o, oi) => <div className={`quiz-editor-option${o.is_correct ? " correct" : ""}`} key={oi}><label><input type={q.question_type === "multiple" ? "checkbox" : "radio"} name={`correct-${qi}`} checked={o.is_correct} onChange={(e) => updateQuestion(qi, { options: q.options.map((x, i) => ({ ...x, is_correct: q.question_type === "multiple" ? i === oi ? e.target.checked : x.is_correct : i === oi })) })} /><span><Check aria-hidden="true" size={14} /><span className="visually-hidden">Правильный ответ</span></span></label><input value={o.text} placeholder={`Вариант ${oi + 1}`} onChange={(e) => updateQuestion(qi, { options: q.options.map((x, i) => i === oi ? { ...x, text: e.target.value } : x) })} /><button type="button" aria-label={`Удалить вариант ${oi + 1}`} onClick={() => updateQuestion(qi, { options: q.options.filter((_, i) => i !== oi) })}><Trash2 aria-hidden="true" size={15} /></button></div>)}<button type="button" className="quiz-add-option" onClick={() => updateQuestion(qi, { options: [...q.options, { text: "", is_correct: false }] })}><Plus aria-hidden="true" size={15} />Добавить вариант</button></div></article>)}<button type="button" className="button secondary add-question-button" onClick={() => setQuestions((all) => [...all, { question: "", question_type: "single", options: [{ text: "", is_correct: true }, { text: "", is_correct: false }] }])}><Plus aria-hidden="true" size={17} />Добавить вопрос</button></div>}
      </section>
      <footer className="editor-save-bar"><span>{initial.id ? "Сохраните изменения перед возвратом к программе" : "Урок добавится в выбранный модуль"}</span><button className="button" disabled={pending}><Save aria-hidden="true" size={18} />{pending ? "Сохраняем…" : "Сохранить урок"}</button></footer>
    </div>
  </form>;
}
